--here u require all the plugins 
require("core/plugin_config/colorscheme")
require("core/plugin_config/lualine")
require("core/plugin_config/neotree")
require("core/plugin_config/dashboard")
require("core/plugin_config/lsp")
require("core/plugin_config/cmp_nvim")
require("core/plugin_config/autopairs")
require("core/plugin_config/fzf")
require("core/plugin_config/null-ls")
require("core/plugin_config/prettier")
require("core/plugin_config/bufferline")
require("core/plugin_config/vimtex")
