return {
	 "xiyaowong/transparent.nvim" ,

	opts = {

groups = { -- table: default groups
		"Normal",
		"NormalNC",
		"Comment",
		"Constant",
		"Special",
		"Identifier",
		"Statement",
		"PreProc",
		"Type",
		"Underlined",
		"Todo",
		"String",
		"Function",
		"Conditional",
		"Repeat",
		"Operator",
		"Structure",
		"LineNr",
		"NonText",
		"SignColumn",
		"CursorLineNr",
		"EndOfBuffer",
		"NeoTreeNormal",
		"NormalFloat",
		"NeoTreeNormalNC",
		"NeoTree",
		"NvimTree",
		"File Explorer",
	},
	extra_groups = {
     "BufferLineFill",
                "BufferLineBackground",
                "BufferLineBufferSelected",
                "BufferLineBufferVisible",
                "BufferLineSeparator",
                "BufferLineSeparatorSelected",
                "BufferLineSeparatorVisible",
                "BufferLineIndicatorSelected",
                "BufferLineIndicatorVisible",
                "BufferLineCloseButton",
                "BufferLineCloseButtonSelected",
                "BufferLineCloseButtonVisible",
                "BufferLineTab",
                "BufferLineTabSelected",
                "BufferLineTabClose",
                "BufferLineModified",
                "BufferLineModifiedSelected",
                "BufferLineModifiedVisible",
		"NormalFloat",
		"NvimTreeNormal",
		"NvimTreeNormalNC",
		"NvimTreeNormalFloat",
		"NvimTreeEndOfBuffer",
		"NeoTreeCursorLine",
		"NeoTreeDimText",
		"NeoTreeDirectoryIcon",
		"NeoTreeDirectoryName",
		"NeoTreeDotfile",
		"NeoTreeFileIcon",
		"NeoTreeFileName",
		"NeoTreeFileNameOpene",
		"NeoTreeFilterTerm",
		"NeoTreeFloatBorder",
		"NeoTreeFloatTitle",
		"NeoTreeTitleBar",
		"NeoTreeGitAdded",
		"NeoTreeGitConflict",
		"NeoTreeGitDeleted",
		"NeoTreeGitIgnored",
		"NeoTreeGitModified",
		"NeoTreeGitUnstaged",
		"NeoTreeGitUntracke",
		"NeoTreeGitStaged",
		"NeoTreeHiddenByName",
		"NeoTreeIndentMarker",
		"NeoTreeExpander",
		"NeoTreeNormal",
		"NeoTreeNormalNC",
		"NeoTreeSignColumn",
		"NeoTreeStatusLine",
		"NeoTreeStatusLineNC",
		"NeoTreeVertSplit",
		"NeoTreeWinSeparator",
		"NeoTreeEndOfBuffer",
		"NeoTreeRootName",
		"NeoTreeSymbolicLinkTarget",
		"NeoTreeTitleBar",
		"NeoTreeWindowsHidden",
	}, -- table: additional groups that should be cleared
	exclude_groups = {}, -- table: groups you don't want to clear
	}, 
}

